services:
  app:
    image: alpine:latest
    restart: always
    init: true
    working_dir: /app
    volumes:
      - ./dist/gpstrack_linux_amd64_v1:/app
      - ./public:/app/public
      - ./cert:/app/cert
    network_mode: host
    command: ["/app/gpstrack", "12000", "12050"]
    env_file: .env
