services:
  app:
    build: .
    restart: always
    init: true
    working_dir: /app
    volumes:
      - ./dist/gpsmap_linux_amd64_v1:/app
      - ./gpsmap.toml:/root/gpsmap.toml
      - ./.data/sqlite:/var/lib/gpsmap
      - ./.data/server.crt:/root/server.crt
      - ./.data/server.key:/root/server.key
    network_mode: host
    command: ["/app/gpsmap", "-c", "/root/gpsmap.toml"]
