services:
  app:
    build: .
    restart: always
    init: true
    working_dir: /app
    volumes:
      - ./dist/gpstrack_linux_amd64_v1:/app
      - ./public:/app/public
      - ./.data:/app/.data
    network_mode: host
    command: ["/app/gpstrack", "-http", "0.0.0.0:12000", "-gprs", "0.0.0.0:12050"]
    env_file: .env
