dbfile = "/var/lib/gpsmap/db.sqlite3"
keepdays = 30
tz = "Europe/Vilnius"
debug = false

[http]
bind = "0.0.0.0:12000"
certfile = "/root/server.crt"
keyfile = "/root/server.key"
username = "admin"
password = "admin" # change it!

[gprs]
bind = "0.0.0.0:12050"

[tgbot]
token = ""
timeout = 3730
